### ISSUE TITLE
Dlc/SotV Broken skill icons

### ISSUE THREAD

**Issue by Tsukino-uwu** [Vl4dimyr/BanditWeaponModes#1]
Figured this mod would be similar to the captain one so decided to get a log for this one as well
[LogOutput.log](https://github.com/Vl4dimyr/BanditWeaponModes/files/8201845/LogOutput.log)
Only bepin, Hookgen patcher, r2api & BanditWeaponModes were used with no prior configs or other mods to conflict with
`[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly UnityEngine.Input, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
BanditWeaponModes.BanditWeaponModesPlugin.Update () (at <8890b38119854b2ab8eae2befc5f86b5>:IL_0001)` 

`[Error  : Unity Log] MissingMethodException: void TMPro.TMP_Text.SetText(string)
Stack trace:
DMD<>?-193534464.Hook<RoR2.UI.SkillIcon::Update>?1082912768 (RoR2.UI.SkillIcon ) (at <acedb4f7f4fc49639fa76eb136004348>:IL_0014)`

**Comment by Bogdanov89** [comment]
would be great if this was updated, please :)

**Comment by Vl4dimyr** [comment]
Sorry this took so long!
